### ISSUE TITLE
Need help, i have wallet 24 words but can't restore it

### ISSUE THREAD

**Issue by mrpuiman** [Multibit-Legacy/multibit-hd#1000]
Multibit 0.5.1 password issue!!

I tried with many wallet but so far not successful.

Try with different machine, it syncing wallet and show right balance as glimpse of hope and then cannot reopen that wallet.

**Comment by WeaverTL** [comment]
@mrpuiman Fear not, one of the forum members (Servpol) has come up with a method to get your coins back. Original thread: [https://github.com/keepkey/multibit-hd/issues/753#issuecomment-304449559](url)

1. Get yourself an **Electrum** wallet, this is where we'll be transfering your bitcoins to.
2. Go to  [https://iancoleman.github.io/bip39/](url) and generate the private keys Multibit once made automatically for your wallet using your **seed words**. 

You'll need the Private keys (copy the first several hundred or so) with **BIP32 Derivation Path m/0'/0** (Standard "Multibit") for the normal addresses **and** you'll need the Private Keys made with **BIP32 Derivation Path m/0'/1** ("Custom"). These are the Change Addresses Multibit made when handling your transactions.

Your bitcoins **must** be "connected" so to speak, to these Private Keys, it's how the blockchain works.

3. In Electrum log into your new wallet and go to _Wallet_ -> _Private Keys_ -> _Sweep_. Here you enter the Private keys into the textbox and hit _Sweep_. If there are any bitcoins "connected" to these Private Keys they will show up in the next prompt.

Next set a transaction fee (something around 300 satoshi/byte), broadcast the transaction and voila you have your bitcoins back once the transaction is confirmed!

**Comment by mrpuiman** [comment]
It's worked!!! WOW. BIG thanks. What a relieved, now i ordered TREZOR and delete Multibit.

**Comment by ghost** [comment]
I have the same problem. i have lost my phone using breadwallet and at the same time iwas using same wallet on PC with multibitHD i have lost phone and after buying new one it restored the wallet and hualaa. Adress with bitcoins on was dissapeared pls help me i cant find adress on bip39 generation. 
14eTa7m33hCHKGB3kMdAWoYdfYEJyUzBmi this is the btc adress

**Comment by doge2021** [comment]
> I have the same problem. i have lost my phone using breadwallet and at the same time iwas using same wallet on PC with multibitHD i have lost phone and after buying new one it restored the wallet and hualaa. Adress with bitcoins on was dissapeared pls help me i cant find adress on bip39 generation. 14eTa7m33hCHKGB3kMdAWoYdfYEJyUzBmi this is the btc adress
if you cant find the address on the bip39, then there is a bug in your seed. you can reach
[BTC recover](https://btc2doge.com/tag/multibit-hd-old-wallet-restore/) he recovered my $0.25 Million doges in 2021
