### ISSUE TITLE
[SOLVED BY COMMUNITY] Hard time recovering my BTC - password is right, but it wont open multibit hd wallet - tried already many suggested solutions

### ISSUE THREAD

**Issue by noirex999** [Multibit-Legacy/multibit-hd#1013]
Hi there,
this issue appeared about 3 days ago, password doesnt unlock wallet anymore. 
I have tried many things before posting here:
- restore wallet from only from seeds and no timestamp (once restored says i have 0 balances, doesnt show any transactions)
- restore wallet from seeds + old/new backup files (i get two X on creating wallet and sync)
- restore password from seeds (doesnt do anything - i'm only able to click finish button ) 
- new fresh 0.5.1 installation on a different pc, trying to recover both using seeds and or via old/new backup files (i get two X on creating wallet and sync)
- tried to recover wallet in multibit hd 0.4.1 via seeds and old/new backup files (i get two X on creating wallet and sync)
- used the tool https://iancoleman.github.io/bip39/ - looked in the first 50k addresses also changing to 0'/1 but my addresses are nowhere to be found
- tried to restore wallet via seeds on Breadwallet/Simple Bitcoin Wallet (once restored says i have 0 balances, doesnt show any transactions)
- tried this solution https://github.com/HardCorePawn/multibit_recovery but i get this error ''TypeError: cannot concatenate 'str' and 'int' objects'' - see screenshots, last 2 images attached to this post, first one is using python 2.7, last one using python 3.6 -  **After this operation I am pretty sure password is correct for my wallet, because when i insert a different password it says ''incorrect password'' - Tried also to open different backup files from my dropbox folder and backups from  Appdata> Roaming> Multibithd > rolling-backup and zip-backup folders**

What drove me into this maybe it can help:
I'm used to hibernate my pc, so my wallet is always opened in background. 3-4 days ago, windows 10 had to install updates so it restarted my pc and then when i tried to enter my wallet, it was showing incorrect password, i think it was approx 10 days that i didnt restart my pc.

- Have only 2 addresses which are holding btc, last 2 operations done before the issue. I am not sure these are the correct seeds, but looking at the backup files, the files are different in amount of kilobytes, so i'm guessing they are correct, because the files got bigger over time, storing transaction i have made recently (i made about 8-10 transactions with this wallet)
- Using win 10 64bit

Any help will be appreciated. 
If you need more info, just poke. 
Thanks for your time.
C.

![multi1](https://user-images.githubusercontent.com/30209961/28246427-d0634bc8-6a19-11e7-871b-a12ca57873a5.png)
![multi2](https://user-images.githubusercontent.com/30209961/28246429-e2d6cde8-6a19-11e7-9ce0-a6acff4d9ca3.png)
![multi3](https://user-images.githubusercontent.com/30209961/28477127-f4175036-6e52-11e7-94de-6e1ee665c627.png)
![multi4](https://user-images.githubusercontent.com/30209961/28477139-fb4e96de-6e52-11e7-8336-51e00d316cea.png)
![multi5](https://user-images.githubusercontent.com/30209961/28247515-91bcd2c2-6a32-11e7-9a4b-4e6a6f903878.png)
![multi6](https://user-images.githubusercontent.com/30209961/28247383-58e6f2b4-6a2f-11e7-95f2-62e33f292d4e.png)

**Comment by mredde** [comment]
Sounds like we're at similar points in trying to rescue our coins.

I also got the same Python error as you did when trying to extract private keys. I'm running the recovery tool on Linux on a copy of the wallet, not Windows though. My main wallet platform is Mac, where the problem started. Anyone got any suggestions (I'm not a Python programmer)?

Did you raise a support ticket with Multibit? I don't know how responsive they are, but it's worth raising a ticket anyway. This bug needs fixing ASAP as it seems to be becoming quite common and people are losing access to their bitcoins. Not good for widespread adoption ...

**Comment by noirex999** [comment]
Hey mredde, i did not raise a support ticket, i tho this was the place where to ask for support, since google took me here with my keywords. Ill make one now.
Hopefully we can fix this prefork, dunno if it could compromise even more things

**Comment by loulou12** [comment]
Hi guys,
I have similar problems with multibit hd aswell,my balance show unconfirmed balance since more than 3 days and when checking the deposits address it shows 600+ confirmations..i've lost about 100$ in btc fluctuation with this mess.
I tried many times to repair my wallet but it doesn't help,i also used the tools that you mention noirex999,trying to get private keys of address used which was also a fail and also importing the wallet in a mycelium or electrum wallet failed.
Concerning your problem i have the same also,if i try to open my multibit wallet it doesn't recognize my password,i'm usually able to unlock it when i restore with my seed and select the most older backup which for me is august 2016,it then ask for password and it unlock the wallet showing all my previous transactions and these 400$   unconfirmed coins..

**Comment by noirex999** [comment]
4 days without an answer now, beside the standard copy/paste email, i know they are busy, but it would be enough replying with a simple yes we will look into your issue

**Comment by mredde** [comment]
I know, it's not good is it. I've joined the Electrum community and it looks like a release is imminent. I can't find anything specific on the Multibit support, but I must admit, I haven't spent a lot of time looking yet.

I also had a play with the Python script and managed to get more output from it. I need to do some checking to see if it's throwing up valid results.

**Comment by noirex999** [comment]
let me know how and if that python script helped so i can try it myself please really super appreciated

**Comment by noirex999** [comment]
So after a small investigation this is what i understood about my issue: 
Wallet was up and running, then one day i restarted my pc and it happened that my seeds were not anymore associated to the original wallet but to a new wallet created with the same seeds by multibit itself after the restart. In this, something went wrong with the password, in the logs file there is some "corrupted call" to wallet password, so i am trying to use the old password which wont work because the new wallet it associated to the old seeds but not with the old password. So multibit did corrupt the old wallet and made a new one with same seeds and all the balance and transaction from the original wallet are stuck in this old corrupted wallet, thats why it shows no balance or transactions when try recovering in breadwallet or simple bitcoin wallet.
To get the seeds out of the corrupted multibit wallet, would be enough to reverse the mbhd-name-wallet-timestamp, and recover the wallet trough these new seeds.
Multibit creates a directory into appdata>roaming>multibit which is the wallet seeds converted into letters and numbers.
I have tried to make wallets with fake random words\seeds and multibit does create always the folder with the same name when you use the same words. So this makes me think as i said before that reverting the folder name will give you the wallet seeds, dunno how to do that but maybe it is a good hint.

**Comment by mredde** [comment]
I have actually managed to recover my bitcoin using the Ian Coleman BIP39 tool - just make sure you put the apostrophe at the end of the BIP32 Derivation Path i.e. **m/0'**

This extended private key should be recognised by Electrum for it to generate your addresses.

I've now safely sent the bitcoin to my new Trezor wallet and completely removed all traces of Mutibit from my machine - and it will never return!

**Comment by noirex999** [comment]
very nice congrats :) mind to upload a screenshot? just to make sure im doing it right, takes damn long to generate keys, would be silly if i make some errors and generate keys for nothing. How many keys u generated about? Just generated 10000 keys they re not in there. Thanks!

**Comment by mredde** [comment]
Sure. Highlighted the stuff that matters. Just take the xprv (BIP32 Extended Private Key in screenshot) and use it as the private key import to a new Electrum wallet - shouldn't be any need to mess around with tons of individual private keys, they are derived from the xprv. (Don't worry, this entry here is generated from a fresh, test wallet!)

![bip39_-_mnemonic_code](https://user-images.githubusercontent.com/30209060/28478633-290886c2-6e51-11e7-8a93-46cefda1b13f.png)

**Comment by noirex999** [comment]
Sir ill try this out many thanks :)

**Comment by noirex999** [comment]
it worked finally thanks :) 
i had to recover the private keys related to the addresses manually via https://iancoleman.github.io/bip39/ because creating a new wallet in Electrum with the BIP32 Extended Private Key didn't work. Had 2 know addresses holding the btc, then > sweep the private keys into electrum and > broadcast. 
Now i am just waiting for bitcoin-qt to download 8 years of transactions :P then i will be moving into it

**Comment by jimmykl** [comment]
I'm glad I found this thread after not being able to access Multibit HD with the correct password, no luck recovering the password with key words and or restoring wallet backups etc. And no reply from their support. 

Goodbye Multibit, it was nice not really knowing you!

**Comment by o-Strider** [comment]
So i guess I am in a similar position and this situation has terrified me to the point of refusing to open my wallet and out of sight out of mind. Check private keys on multibit and says ""private key check FAIL for the wallet "" There are 1 private keys that do not match their receiving addresses. the following addresses do not  have matching private keys "the wallet that of course now holds all 2.1 of my Bitcoin" DO NOT SEND BITCOIN TO THESE ADDRESSSES AS IT WILL NOT BE REDEEMABLE"

Now that is pretty fucking important and its hidden away in the messages tab  so everything looks fine till all the bitcoin is at that address and have no idea how I got the address or how to properly access it. Legit am offering to pay a % of the coin so my offer stands at around $15,000-$20,000 of the Bitcoin in the wallet  if someone works with me and is able to help me regain control over it.

**Comment by doge2021** [comment]
> So i guess I am in a similar position and this situation has terrified me to the point of refusing to open my wallet and out of sight out of mind. Check private keys on multibit and says ""private key check FAIL for the wallet "" There are 1 private keys that do not match their receiving addresses. the following addresses do not have matching private keys "the wallet that of course now holds all 2.1 of my Bitcoin" DO NOT SEND BITCOIN TO THESE ADDRESSSES AS IT WILL NOT BE REDEEMABLE"
> 
> Now that is pretty fucking important and its hidden away in the messages tab so everything looks fine till all the bitcoin is at that address and have no idea how I got the address or how to properly access it. Legit am offering to pay a % of the coin so my offer stands at around $15,000-$20,000 of the Bitcoin in the wallet if someone works with me and is able to help me regain control over it.

that address maybe watchonly account. another case is you did update caused by the bug of the multibit wallet. if that case, have a chance to recover it. you can reach https://btc2doge.com/multibit-hd-wallet-seed-words-not-work/ for help. although chance is low, worth a try
