### ISSUE TITLE
Can't connect with multibit-hd but can with multibit classic

### ISSUE THREAD

**Issue by owen-kellie-smith** [Multibit-Legacy/multibit-hd#724]
Maybe relates to  #707 .

  Operating System: Ubuntu 14.04
  MultiBit HD Version: Don't know.  I downloaded multibit-hd-unix-0.1.3.sh from https://multibit.org/download.html on approx 10 Sep 2015.
  Steps to replicate the problem:
1. Start Multibit-HD. Enter wallet password.  Screen gets stuck on "Connecting to Bitcoin network"

![multibit-wallet-startup](https://cloud.githubusercontent.com/assets/7147546/9954624/7a993558-5de2-11e5-87fd-0b8d60fa38e8.png)

By contrast: Start Multibit-classic.  Multibit-classic connects OK.
![classic-connected](https://cloud.githubusercontent.com/assets/7147546/9954644/9cc44ee2-5de2-11e5-9bd0-f295da235869.png)

**Comment by jim618** [comment]
Does this happen 100% of the time you open MultiBit HD and on every network ? Normally this is firewall issues but CLassic and HD use essentially the same network code so that isn't very likely

**Comment by gary-rowe** [comment]
Also, is Classic really synchronising (i.e. you can see transactions)? There may be a UI update issue in the Classic sync progress bar.

**Comment by owen-kellie-smith** [comment]
@jim618  No, only happens on my home wifi - but it happens 100% of the time I open Multibit HD on the home wifi.  It doesn't happen at all (i.e. HD works fine) on the network tethered to my phone.

@gary-rowe Yes, Classic is really synchronising.  I just sent it 1 mB and it appeared practically immediately.
![classic-in-sync](https://cloud.githubusercontent.com/assets/7147546/9964898/d0f06f0a-5e2a-11e5-8807-c72aabe8e2e5.png)

**Comment by owen-kellie-smith** [comment]
Closing as multibit is deprecated. See https://github.com/Multibit-Legacy/multibit-hd/blob/develop/README.md.
