### ISSUE TITLE
Payment our of Multibit HD is stuck at "sending"

### ISSUE THREAD

**Issue by trick345** [Multibit-Legacy/multibit-hd#935]
Bug report
  Operating System: windows 10
  MultiBit Version: 0.4.1
  Steps to replicate the problem:
1. I have two payments im trying to send but they wont proceed past the "sending" stage. i have tried "repair wallet" several times, but it doesn't solve the problem

![screenshot 2016 10 26 21 01 51 png](https://cloud.githubusercontent.com/assets/23084455/19740602/960a4f18-9bbf-11e6-92f3-cc2136ca5e02.png)

**Comment by kliyer** [comment]
Hi trick345, sorry to hear you are facing issues with MultiBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.
