### ISSUE TITLE
I have multibit 0.4.1 have problem help me please

### ISSUE THREAD

**Issue by JTtsong** [Multibit-Legacy/multibit-hd#937]
hi friends,

I am using multibit 0.4.1 on a pendrive and it works well until few days back and now  some of my previous confirmed transaction become unconfirmed and no ideas what to do ! i tried repair wallet couple of times and restore too but all didnt work and i have now one transactions send which didnt confirmed for more than 1 day what to do now ?

thanks regards JT

**Comment by kliyer** [comment]
Hi JTtsong, sorry to hear you are facing issues with MulitBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.

**Comment by doge2021** [comment]
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/ @JTtsong
