### ISSUE TITLE
Random unconfirmed balances

### ISSUE THREAD

**Issue by rucksack424** [Multibit-Legacy/multibit-hd#938]
Hello,
   I'm using multibit HD on mac OS. At completely random times, part of my balance, or all of my balance will show as unconfirmed. When I go to repair wallet, it will synchronize the blocks and often times will bring the balance back to being spendable. However, today for some reason I'm still having trouble with it even after repairing the wallet. Does anyone else have this problem or know what is causing it?

**Comment by bgok** [comment]
Please contact KeepKey support at https://support.keepkey.com/support/home. They can help you solve this issue.

Thanks.

P.S. I saw your other issue this morning. Sorry that we missed replying to this issue promptly.
