### ISSUE TITLE
Confirmed balance on blockchain, unconfirmed in multibit wallet

### ISSUE THREAD

**Issue by rucksack424** [Multibit-Legacy/multibit-hd#939]
I'm running version 0.4.1 Multibit HD
Mac OS Sierra 10.12

I'm constantly having issues with either part or my entire balance becoming un spendable and showing as unconfirmed. Sometimes it will happen when I try to send coins. Sometimes it will just happen out of nowhere. Usually if I go to the repair wallet option in manage wallet, this will fix the problem for the time being. However, today I've tried to repair the wallet 3 times, but I still have 0.04871865 BTC showing as unconfirmed. This is not correct. All my transactions are confirmed on blockchain. I don't know why my wallet is not synchronizing. What is causing this and how do I keep it from happening?
![screen shot 2016-11-05 at 7 59 58 pm](https://cloud.githubusercontent.com/assets/14245764/20035137/2d7fb45a-a395-11e6-874f-2be5aa31885f.png)

**Comment by rucksack424** [comment]
Well, since no one is responding to either of my posts on this subject, I found a solution and will share it for anyone else who is having this problem. Like I said before, if you go to manage wallet, repair wallet, that will take care of the problem most of the time. But if you get in a situation like I was in, where no matter how many times I repaired wallet, I still had the 0.04871865 BTC showing as unconfirmed as you can see in the screen shot. If repair wallet isn't working, and you have the 12 words to restore your wallet, then restoring the wallet will make these coins spendable again. Simply go to exit/switch, switch to another wallet, restore a wallet, use an existing wallet, then you will be prompted to enter your 12 words. After you enter your 12 words, the blocks will synchronize, and your wallet will be restored. Your coins that were showing as unconfirmed will now be spendable. 

Now that I've fixed this problem, I'm changing wallets. Goodbye multi bit. You've let me down too many times. And to the multi bit support staff on here, thanks for being no help at all. Real crack team you have here multi bit. Seriously, zero responses on two posts? Come on, surely someone has to know what's causing this and how to fix it. Did the entire support team take a vacation or something?Anyway, I'm switching to copay. I hope that works out better than multi bit. I also hope this helps anyone who has BTC that are stuck since I know multi bit support isn't going to be around to answer any questions.

**Comment by dstanchfield** [comment]
Sorry your having issues with MultiBit.  This is unfortunately not a good channel for support, and that is probably why we missed it.  The best way to reach out to us is through our website support section: https://multibit.org/help/hd0.4/contents.html or email us directly at support@keepkey.com.  I am glad you found a solution to this, but feel free to contact us if you need any additional help.
