### ISSUE TITLE
Lost Request, how to retrieve

### ISSUE THREAD

**Issue by 99bits** [Multibit-Legacy/multibit-hd#940]
Hi, I created a payment request which generated an address, then I gave out the address and accidentally deleted the request. Is there any way to get coins that were sent to the address? Can I manually re-add the address and does Multibit HD know the key?   I tried Tools Repair but do not see the address.

**Comment by kliyer** [comment]
Hi 99 bits,  although your  request was deleted the wallet recognizes the address generated by it. So  the coins sent to that address should be received by your wallet. For further assistance I would suggest you contact our support portal at https://keepkey.freshdesk.com/support/solutions

**Comment by doge2021** [comment]
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/
