### ISSUE TITLE
HiDPI support and crash in OpenJDK-9-jre 

### ISSUE THREAD

**Issue by ghost** [Multibit-Legacy/multibit-hd#941]
## The issue
- ubuntu16.04 with xfce, on mbp with 220dpi display
- multibit-hd 0.4.1 or 0.5 beta

The **actual issue** is, no HiDPI support with openjdk8. the whole UI is extremely small. While MultibitClassic's UI is in the right DPI scaling.

## Might be another issue.
Trying to test this in openjdk9, but program crashes.
err_log attached. 

[hs_err_pid22230.log.txt](https://github.com/keepkey/multibit-hd/files/580180/hs_err_pid22230.log.txt)

**Comment by kliyer** [comment]
Hi kensenjiha, sorry to hear you are facing issues with MulitBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.
