### ISSUE TITLE
Fixed size transaction overview view 

### ISSUE THREAD

**Issue by limbenjamin** [Multibit-Legacy/multibit-hd#942]
The UI displaying transaction overview is fixed in size. This causes issues when a transaction has too many addresses associated with it. The "next" and "cancel" buttons get pushed off the screen and is no longer visible. There is no scrollbar and mousewheel scrolling does not work. Therefore, I am unable to access the subsequent transaction amount and detail view.

![untitled](https://cloud.githubusercontent.com/assets/3461825/20244655/4be948bc-a9c5-11e6-8be7-8d966c932db2.png)

**Comment by kliyer** [comment]
Hi limbenjamin , sorry to hear you are facing issues with MulitBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.

**Comment by limbenjamin** [comment]
This is a UI bug.

**Comment by kliyer** [comment]
Thank you @limbenjamin for reporting the bug, we will look into it.
