### ISSUE TITLE
Description field is overwritten

### ISSUE THREAD

**Issue by ebonit** [Multibit-Legacy/multibit-hd#943]
If I create a send transaction and I add something to the description field, the message I write there is overwritten with the recipient addresses.

The last send transaction that I can see with the correct description is from August 9 2016.
the first send after that one was on October 20th and that one does not show the description anymore.  It must have been an update between these two dates that broke it.

**Comment by kliyer** [comment]
Thank you for reporting the bug @ebonit. We will look into it.
