### ISSUE TITLE
Question: Is Multibit more secure than Bitcoin Armory?

### ISSUE THREAD

**Issue by ghost** [Multibit-Legacy/multibit-hd#945]
Bitcoin Armory is clearly outdated for a very long time.
What are the benefits of using multibit over bitcoin armory besides the fact that its more up to date?
Is it more secure than what bitcoin armory ever was?

**Comment by kliyer** [comment]
Hi @Beast141, sorry for the delayed response. MultiBit and Bitcoin Armory are very different.I would suggest you look at both the softwares based on your requirements.
