### ISSUE TITLE
Transaction is not approved after more than 3 days

### ISSUE THREAD

**Issue by alexvirtech** [Multibit-Legacy/multibit-hd#946]
Hi, I sent transaction from MultiBit to BitGo wallet address. 
I see the transaction both in MultiBit (as sending) and in BitGo (as received), but it is not approved already for 3 days. 
The transaction ID in blockchain.info: e0eca819631fa5ae399f8bda67724a131c489cf90fe1048b56aa118ad6214916
Please, see attached screenshots from MultiBit, BitGo and blockchain.info.
![b1](https://cloud.githubusercontent.com/assets/4235427/20625782/0583ec08-b31e-11e6-9230-0f36e8e088d1.PNG)
![b2](https://cloud.githubusercontent.com/assets/4235427/20625783/0586408e-b31e-11e6-97d7-a080c9caadf3.PNG)
![b3](https://cloud.githubusercontent.com/assets/4235427/20625784/0586d904-b31e-11e6-86da-f0c3ffafc4d9.PNG)

**Comment by kliyer** [comment]
Hi @alexvirtech  sorry to hear you are facing issues with MulitBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.
