### ISSUE TITLE
Balance is suddenly Unconfirmed?

### ISSUE THREAD

**Issue by forty2oz** [Multibit-Legacy/multibit-hd#947]
![image](https://cloud.githubusercontent.com/assets/7319268/20820159/c338ac2c-b7fe-11e6-8702-9e7465b34602.png)

![image](https://cloud.githubusercontent.com/assets/7319268/20820190/fbdd88d6-b7fe-11e6-9a90-78085e2fde98.png)

Hey Jim, looks like this issue was discussed back in February. Just happened to me. I tried the fix you described <a href="https://bitcointalk.org/index.php?topic=1361928.msg13927284#msg13927284">here</a> where I rename the wallet folder to get Multibit to start from scratch but it did not work.

These transactions are confirmed on the network:

![image](https://cloud.githubusercontent.com/assets/7319268/20820726/f343ab84-b802-11e6-9005-7e0f433cdf5b.png)

Please advise sir - this is a sizeable chunk of change!

Matt

**Comment by kliyer** [comment]
Hi @forty2oz,  sorry to hear you are facing issues with MulitBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.

**Comment by vanboohen** [comment]
Do you still have wallet files and password ?
