### ISSUE TITLE
Wallet shows all balance as "unconfirmed"  

### ISSUE THREAD

**Issue by ghost** [Multibit-Legacy/multibit-hd#948]
When opening my wallet all my balance is ZERO and what was supposed to be my balance is displayed as unconfirmed transactions. I cannot send or receive transactions in this state.

I do a costly repair wallet and it fixes the issue, but every day or so the same problem happens

**Comment by kliyer** [comment]
Hi @gustavonalle , sorry to hear you are facing unconfirmed balance issues with MultiBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.

**Comment by dandv** [comment]
@kliyer: this is a useless answer. The Freshdesk DB has nothing about unconfirmed transactions.

I liked MultiBit Classic, but HD has a horrible user interface, and to not confirm a transaction two weeks after the fact is unacceptable. I'll uninstall and never use again after I (hopefully) recover my coins.

A more useful discussion is in #862.
