### ISSUE TITLE
Restore wallet from seed appears to hang

### ISSUE THREAD

**Issue by mikeashley** [Multibit-Legacy/multibit-hd#950]
This is with version 0.4.1.

I have been using multibit-hd successfully on Ubuntu.  I'm trying it on Windows 10.  I can create a new wallet, and the client connects to the Bitcoin network with 10 peers.  If I then go to restore an existing wallet from wallet words, the client stops at wallet synchronization and doesn't show progress or completion.  The network status indicator is red.  If I go ahead and exit the dialog, the wallet is not available for use from the wallet selection dropdown.

The behavior looks identical to what was reported in #107.

**Comment by kliyer** [comment]
Hi @mikeashley , sorry to hear you are facing issues with MulitBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions
