### ISSUE TITLE
Multibit HD can't connect to network on startup

### ISSUE THREAD

**Issue by chutchut** [Multibit-Legacy/multibit-hd#953]
Version 0.4.1 
System: 
3.13.0-106-generic #153-Ubuntu SMP Tue Dec 6 15:44:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Ubuntu 14.04.5 LTS (Xubuntu)

Multibit HD has been working fine, something must have changed because now it will not connect to the Bitcoin network. I have tested my local network by installing the same version (0.4.1) in a Lubuntu VM and it connects and syncs as normal. 

I have re-installed the program and the problem still exists. The only seemingly relevant messages in the logs are as follows:

[2016-12-22 16:17:09,936] DEBUG [AWT-EventQueue-0] o.m.h.u.v.c.Panels - Show light box 
[2016-12-22 16:17:09,943] DEBUG [AWT-EventQueue-0] o.m.h.u.v.c.p.LightBoxPanel - Light box panel added to application frame 
[2016-12-22 16:17:20,774] ERROR [PeerGroup Thread] o.b.c.PeerGroup - Peer discovery failure, class:org.bitcoinj.net.discovery.PeerDiscoveryException, message:No peer discovery returned any results: check internet connection? 
[2016-12-22 16:17:40,775] ERROR [PeerGroup Thread] o.b.c.PeerGroup - Peer discovery failure, class:org.bitcoinj.net.discovery.PeerDiscoveryException, message:No peer discovery returned any results: check internet connection? 
[2016-12-22 16:18:00,776] ERROR [PeerGroup Thread] o.b.c.PeerGroup - Peer discovery failure, class:org.bitcoinj.net.discovery.PeerDiscoveryException, message:No peer discovery returned any results: check internet connection?

**Comment by chutchut** [comment]
Have now repaired the wallet twice on my primary machine, each time after completing this process my balance is unconfirmed and stays in that state. If I quit and re-open the application on my primary machine the PeerDiscoveryException re-occurs and i'm forced to repair again.. 

On the VM with a fresh install of MBHD 0.4.1 and no existing wallet or backups if I restore from the seed words I face exactly the same issue, my entire balance is unconfirmed., but at least I can connect to the network as expected. 

This is a wallet I have had (and not used) since July 2015, the confirmations occurred way back then.

Starting to worry now and losing faith and confidence in this software, please advise.

**Comment by kliyer** [comment]
Hi @chutchut  sorry to hear you are facing issues with MulitBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions

**Comment by forty2oz** [comment]
Hey man, experienced a similar issue. Multibit is bugged. The folks at keepkey advised me to download breadwallet on my mobile device and use the wallet words to gain access to my btc on that client. It worked. My paranoid ass immediately downloaded bitcoin core in its entirety on my desktop,  created an address, and transferred my btc from breadwallet over. Hope this helps

**Comment by chutchut** [comment]
hi @kliyer why have you prematurely closed this issue? Thanks @forty2oz i will give that a try..

**Comment by forty2oz** [comment]
It's on ongoing issue with Multibit from what I can tell. They're working on it. In the meantime, not safe - maybe try them again once the issue is resolved

**Comment by chutchut** [comment]
Yea seems so. I tried the breadwallet app on my Android but it kept freezing. I actually resolved it on my VM by downgrading to the version of Multibit HD (v.0.1.1) that the wallet was created with and doing a seed restore. Gonna try that on my main machine now. But its goodbye to Multibit for me after this, im going to use Electrum from now on. Cheers!

**Comment by forty2oz** [comment]
As long you have secure access to your btc - win!

**Comment by Forage** [comment]
I'm experiencing the same issue now, with Multibit HD 0.4.1 as well. Why was this bug closed without providing a solution?

**Comment by Struppi** [comment]
I use 0.5.1 and run in the same problem. Did you all change your wallet client?

**Comment by Forage** [comment]
@Struppi check out bug #967, I found a work-around for my issue yesterday. Try if this does the trick for you as well and let the developers know (if they are ever going to bother looking at any of the issues again) by reporting in that bug's comments.

**Comment by Struppi** [comment]
LOL - I actually did it in the same moment. and I read my message here because I want link to your Thread. 

I was a bit curios, because at the last time I used it works. But anyhow, you helped me very much, thanx a lot
