### ISSUE TITLE
0.4.1 - Whole balance unconfirmed after restore from Wallet Words

### ISSUE THREAD

**Issue by kuiperzone** [Multibit-Legacy/multibit-hd#954]
Hi there,

After restoring my wallet from words, and after syncrhonization, my whole balance shows "+Unconfirmed". Reparing wallet, re-start etc., doesn't work.

Wallet can I do to recover?

How can I export this wallet?

**Comment by kuiperzone** [comment]
Oh what the heck. I'll put it down to experience.

**Comment by Rawi666** [comment]
I have exactly the same issue. Repairing my wallet doesn't work (tried multiple times...).
It looks like a large number of people are experiencing the same issue

**Comment by Rawi666** [comment]
I managed to fix my wallet using the following way (simply repairing wallet didn't help XX number of times...).
1. Install Oracle Java 1.8.0 build 112 x64 (x86 didn't work for me)
2. Go to C:\Program Files\MultiBit HD
3. Open command prompt
4. Ensure that when you type "java -version" you can see:
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)
5. Type in command prompt: java -jar multibit-hd.jar
6. Tools->Repair wallet - this time it worked for me (Windows 10 x64)

**Comment by kuiperzone** [comment]
I managed to resolve my own problem by porting my BIP39 wallet words to another wallet. The java version issue will hopefully help others. Sounds a lot easier than what I did. :)

**Comment by doge2021** [comment]
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/
