### ISSUE TITLE
Lost my bitcoins even though all were sent to the exact same address

### ISSUE THREAD

**Issue by bitcoinman500000** [Multibit-Legacy/multibit-hd#955]
I sent 4 transactions 0.02 BTC and 0.01 3 times to a company called bit blender and only one of the transactions posted to my account even though all 4 were sent to the exact same address.  It is has been 5 days or so and still the other 3 have not posted.  Now I lost these coins through no fault of mine.  What happened to them"?  Is there a bug in version 0.5.16  ?  What do I do?

**Comment by kliyer** [comment]
Hi @bitcoinman500000 , sorry for the delayed response. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.
