### ISSUE TITLE
How is this possible?

### ISSUE THREAD

**Issue by vitalis644** [Multibit-Legacy/multibit-hd#960]
Multibit HD is trying to send more money than it received and I have several wallets that are unconfirmed, the rest of the wallets are empty because everything is tied up in sending (for 24 hours) or it's unconfirmed.

I'm at a loss as to how it could be trying to send more than it received...

**Comment by kliyer** [comment]
Hi @vitalis644 , sorry to hear you are facing issues with MulitBit HD. I would suggest you contact the KeepKey Support Desk at https://keepkey.freshdesk.com/support/solutions.
