### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by StevoMcC** [Multibit-Legacy/multibit-hd#977]
I recently uninstalled MultiBitHD after the "Unconfirmed balance" bug. However, now I can't reinstall it. It states that it's not compatible with my version of Windows 7. Anyone got a link to the older x32 version?

**Comment by bgok** [comment]
Old versions of multibit can be found at https://multibit.org/release-info/hd/v0.4.1.html. There is a toggle on the left side of the page that shows a list of version when it is opened.
