### ISSUE TITLE
Stop cluttering my home directory

### ISSUE THREAD

**Issue by yousefamar** [Multibit-Legacy/multibit-hd#978]
I understand that development focus is on MultiBit HD now over classic. While I still use classic, it seems like HD does the same as its predecessor. Please refer to https://github.com/keepkey/multibit/issues/783.

Line in question: https://github.com/keepkey/multibit-hd/blob/master/mbhd-core/src/main/java/org/multibit/hd/core/managers/InstallationManager.java#L163 While hiding the file is a step up, it's still not ideal, and not having dotfiles in the home dir is always better filesystem hacks to work around this.

**Comment by bgok** [comment]
duplicate
