### ISSUE TITLE
I dont know what's happend with my wallet , all transactions are showing unconfirmed.

### ISSUE THREAD

**Issue by eliteuzer** [Multibit-Legacy/multibit-hd#979]
Dear Concern, I am using multibit hd wallet 0.5.1 
![screenshot_1](https://cloud.githubusercontent.com/assets/27822181/25241728/ac12754e-2614-11e7-88b5-24620f35d517.jpg)
and today suddenly my wallet balance started showing unconfirmed and all transactions are showing sending and receiving signs. Now my btc's are showing in unconfirmed stage in wallet but on blockchain explorer they show actual balance. 
kindly help.
![screenshot_1](https://cloud.githubusercontent.com/assets/27822181/25241754/c3db793c-2614-11e7-9152-897f2c9f3415.jpg)
![screenshot_1](https://cloud.githubusercontent.com/assets/27822181/25241761/c996014e-2614-11e7-854f-8527fc053a78.jpg)

**Comment by bgok** [comment]
The software has an unfortunate bug.

Here are some things to try:
- run the repair wallet function
- Downgrade to [version 0.1.0](https://multibit.org/releases/multibit-hd/multibit-hd-0.1.0/)

If neither of these fix the issue and you need to see your correct balance or send transactions right away, try importing your 'wallet words' into [breadwallet](https://breadwallet.com/).

**Comment by williamson20** [comment]
@vikrant6661 
multibit bitcoin wallet has many bugs and issues, and I have solved most of its issues, I can recover your stuck transaction, and lost password for multibit bitcoin wallet file, before, I have recovered several multibit bitcoin wallets for my customers, you can find me at : walletsrecoveryservice@gmail.com

**Comment by doge2021** [comment]
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/
