### ISSUE TITLE
I have a big problem.

### ISSUE THREAD

**Issue by crimefalls** [Multibit-Legacy/multibit-hd#984]
So, my problem is that, whenever I get paid ( via bitcoin ( I use MultiBit as a wallet.) ) Everything works fine, people can send me money.
But for some reason I can't use it, it says, whenever I try to buy something, Low spendable balance detected. some of your bitcoins are tied up with ongoing transactions. Even though I have around 10x the amount needed.
So I read some similar issues, and the answer was to repair your wallet, so I did.But now 80% of my confirmed balance is now unconfirmed, and the issue still persists. Please help. 

Yours Faithfully, Tijn

**Comment by bgok** [comment]
The software has an unfortunate bug.

Try importing your 'wallet words' into [breadwallet](https://breadwallet.com/) will allow you to see your balance and send transactions.

**Comment by doge2021** [comment]
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/
