### ISSUE TITLE
Password error multibitHD 0.5.1

### ISSUE THREAD

**Issue by Lcmaiden** [Multibit-Legacy/multibit-hd#988]
Hi all.

My wallet started making mistakes today. Says my password can not unlock the wallet. I am 100% sure that my password is correct, I have tried to recover the password and to back up and also it does not work. Can someone help me please?

**Comment by cashoncommand** [comment]
It seems to be a BIG PROBLEM..  Nobody is able to get their Bitcoins.
It looks like MULTIBIT have put a backdoor in the wallet and are locking and or Stealing our Bitcoins.

**Comment by bgok** [comment]
Your coins were not stolen. The software has an unfortunate bug.

Try importing you 'wallet words' into [breadwallet](https://breadwallet.com/) will allow you to see your balance and send transactions.

**Comment by doge2021** [comment]
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/
