### ISSUE TITLE
Password not being accepted on the wallet with Bitcoins.

### ISSUE THREAD

**Issue by cashoncommand** [Multibit-Legacy/multibit-hd#989]
I have 3 wallets.  I can login to two of them, but the one with the bitcoins will not accept my password.
I know it is correct..
I have tried to restore it.. but it only comes back with the saying "working" but nothing happens and the Finish button comes up.
I have also tried to restore the wallet, but I the following
![screenshot 2017-05-13 15 03 09](https://cloud.githubusercontent.com/assets/6080781/26089886/5277af9c-3a44-11e7-90ef-07af8f156106.png)

There seems to be an issue with the latest version.. When is this bug going to be fixed and when we will be able to see our bitcoins.

thanks

**Comment by Lcmaiden** [comment]
Happened the same with me yesterday, I tried everything and nothing results unfortunately it seems that we are going to lose all our bitcoins that have given so much work and sweat to win. Still no one takes responsibility and the support does not help at all.

**Comment by cashoncommand** [comment]
Yeah...   I have lost all my Bitcoins..

They need to Resolve this QUICKLY,
 OR  is MultiBit actually stealing our Bitcoins.

**Comment by cashoncommand** [comment]
Can someone for Support please respond with a Resolution and an answer to why we cannot Restore our wallet or display our password.

**Comment by Lcmaiden** [comment]
I found a solution. You download this wallet through an Android or IOS device https://breadwallet.com/.
Then you do not create a wallet, but you do a restoration and insert the seed of your MultibitHd wallet, and then just send the money to another wallet. I hope it helped you.

**Comment by cashoncommand** [comment]
HI Lcmaiden,
Thanks ,, that worked to download the wallet and I see my Bitcoins,

But I am having problems sending them.

It keeps telling me that I have insufficient funds,  I have reduced the amount of bitcoins to cover the fee, but even after reducing it to less then the amount suggested, it still tells me that i don't have enough.

Have you been able to send you bitcoins out of the wallet?

**Comment by Lcmaiden** [comment]
You do not need to add value, just click in the buttom where  say payment and you're done.

**Comment by cashoncommand** [comment]
thanks,, 
ok,   I found it..
When it finally gives you the amount that needs to change to.  You need to select the adjustment.
If you manually put in the amount, it doesn't work.

All good.  I have sent the bitcoins, now waiting for them to arrive to the other side  :)

I see it on the blockchain..


thanks,  You are a LIFE Saver..

**Comment by Romsontech** [comment]
@cashoncommand 
this is the issue which occurs a lot for older versions of multibit, I can recover your wallet if you still have this problem contact me at : walletsrecoveryservice@gmail.com
