### ISSUE TITLE
Fee too low - is there anything I can do?

### ISSUE THREAD

**Issue by Raffa19** [Multibit-Legacy/multibit-hd#991]
Hi
I know this isn't an issue, but my own stupidity, but even so any help would be great!
I've mistakenly tried to send some bitcoins from my Multibit HD wallet to a different wallet that is also mine.  Unfortunately I forgot to check the fee that was attached to the payment, the last time that I used this wallet was almost 12 months ago and it looks like fees have increased several times over in the interim.  So, I've sent it with a fee of 44 sat/B, and current bitcoins.21.co is showing a recommendation of 330 sat/B.  So, it's now been stuck for 3 days, and I'm guessing it may never get picked up by a miner.  There's about 250 quid in the transaction, so I would rather get it back, either returned to my wallet, or successfully sent as soon as possible.  I know some other wallets allow you to increase the fee, or do things like parent pays for child, but can't see any options to do this on Multibit HD.  Any advice, or am I just in a waiting game ... and if so how long will I be waiting for ... forever?
Thanks

**Comment by HelloUniverse0815** [comment]
Same for me here. I didn't use the client for some months, realizing the fee is way too low now. 

Would be interesting in a solution, too.  

It would also make sense to let the client automatically update the appropriate fee after startup, to prevent issues like that, or show some warning this could be a problem.

**Comment by bgok** [comment]
Here's a few things to try:
- the [ViaBTC transaction accelerator](https://www.viabtc.com/tools/txaccelerator/) will accelerate transactions that have fees that are too low.
- You can wait for the transaction to leave the mempool, then repair your wallet.
- If you are using a KeepKey or Trezor, switch to the client software provided with the device.
- If you are not using a hardware wallet, you can use your "wallet words" a compatible wallet. The one I know of is [breadwallet](https://breadwallet.com/).

There is a [knowledge base article](https://multibit.org/help/v0.5/help_support_sentBitcoinFromMultibitButTheyAreStuck.html) for an older version of multibit, but some of the information may still be helpful.
