### ISSUE TITLE
More password not working woes....

### ISSUE THREAD

**Issue by mikelj** [Multibit-Legacy/multibit-hd#994]
I'm really stuck...hope someone can help. Same password problem as others, tried everything & resorted to @ServPol method, but already had unconfirmed transaction on blockchain when this happened. So sequence of events - about a week ago transferred BTC from Multibit HD to Coinbase. Showed as pending in Coinbase, then disappeared...still seen as "sending" in MBHD and after a week finally rejected & pruned from blockchain but now I can't log in to MBHD.
How do I find out what address the BTC were returned to in MBHD so I can look for it at https://iancoleman.github.io/bip39/ ?
I have the seed.

**Comment by WeaverTL** [comment]
@mikelj My best guess is that they were returned to some change address created by Multibit. Try generating the change addresses with m/0'/1 as your BIP32 Derivation Path and look for your remaining bitcoins there.

**Comment by mikelj** [comment]
Thks for reply...hadn't sussed that the derivation path for change addresses was different :-( but was sorted anyway..managed to find an old non-cloud backup of MHD wallet (for which the password seemed to work) and let it sync. This put the unconfirmed tx back on blockchain and used a tx acceleration service to get it through...finally ! This whole MHD password issue is a real pain - can't believe they haven't fixed it yet.

**Comment by doge2021** [comment]
there is bug in old multibit wallet: https://btc2doge.org/multibit-hd-wallet-seed-words-not-work/ @mikelj @WeaverTL @
