### ISSUE TITLE
restore wallet word but no balance

### ISSUE THREAD

**Issue by mrpuiman** [Multibit-Legacy/multibit-hd#999]
1) i have issue with password not open wallet and try to restore using wallet words (24 words)

original wallet in my desktop mac
a- using breadwallet in IOS > Not shown balance
b- using mycelium in IOS > not shown balance

c- using another multibit 0.5.1 on windows desktop > briefly it shown balance after synchronize wallet but again cannot open wallet (same as mac desktop)
d- recover private keys from BIP39 code and restore in electrum wallet > Not shown any balance

- i checked address at blockchain, still balance is there (unspent)

**Comment by mrpuiman** [comment]
Thanks to @WeaverTL. 
Others have this trouble> check https://github.com/keepkey/multibit-hd/issues/1000

**Comment by doge2021** [comment]
do you recovered your coin? www.btc2doge.com can help if you still hold the seed.
